In [ ]:
# Jump Statements:-

In [ ]:
## 1) Break Statements:-
<pre><i>The break is a keyword in python which is used to bring the program control out of loop.</i></pre>

In [4]:
for i in 'Statement':
    if i == 'm':
        break
    print(i)

S
t
a
t
e


In [ ]:
## 2)Continue Statement:-
<pre><i>The continue keyword return control of the iteration to the beginning of the ython program of the python loop or 
python while loop.All remaining lines in the prevailing iteration of the loop are skipped by the continue keyword, which returns execution to the beginning of the next iteration of the loop.</i></pre>

In [6]:
for i in 'Statement':
    if i == 'e':
        continue
    print(i)

S
t
a
t
m
n
t


In [ ]:
## 3)Pass Statement:-
<pre><i>The python 'pass' statement is used to write empty loops.Pass is also used for empty control statements,functions and classes.</i></pre>

In [8]:
if 10 > 5:
    

SyntaxError: incomplete input (3474666645.py, line 2)

In [ ]:
if 10 > 5:
    pass

In [9]:
for i in 'Statement':
    if i == 'a':
        pass
    print(i)

S
t
a
t
e
m
e
n
t


In [ ]:
# Functions:-
<pre><b>A function is a reusable piece of code.Block of statements that does some specific task and returns something.</b>

    1.By including functions, we can prevent repeating the same code block repeatedly in a program.
    
    2.Pthong functions , once defined , can be called many times and from anywhere in a program.
    
    3.If our python program is large , it can separated into numerous functions which is simple to track.
    
    4.The key accomplishment of Python functions is we can return as many outputs as we want with different agruments.

    Syntax of Python Function:-<i>
            def function_name(parameters):
                    # code block
    </i></pre>

In [11]:
# no arguments
def greet():           # Function Declaration
    print("Hello")     # Function Definition
greet()                # Function Call

Hello


In [19]:
# One argument
def greet(name):
    print('Hello' ,name)
    
greet('Subhra')

Hello Subhra


In [ ]:
## return:- it's keyword which is used to return

In [20]:
# One argument
def greet(name):
    return 'Hello '+ name
    
greet('Subhra')

'Hello Subhra'

In [21]:
# two arguments
def add(num1,num2):
    return num1 + num2
    
add(2,3)

5


In [22]:
add(20,30)

50


In [23]:
add(num2 = 55, num1 = 30)

85


In [28]:
# Default Argumens:-
def add(m = 10, n = 12):
    return m + n
add()

22

In [29]:
add(n =30)

40

In [31]:
add(15)

27

In [32]:
add(10,20,30)

TypeError: add() takes from 0 to 2 positional arguments but 3 were given

In [37]:
#Multiple Arguments:
def add1(*arg):
    return sum(arg)

In [38]:
add1(10,23,45,63,24,34,6,7,2,3)


217

In [39]:
add1(23,45,765)

833

In [56]:
# Problem
def isPrime(a):
    fact=0
    for i in range(1,a+1):
        if a%i==0:
            fact+=1
    if fact==2:
        print(a,'is a prime number ')
    else:
        print(a, 'is not a prime number ')
isPrime(23)

23 is a prime number 


In [75]:
#understand to remember
def isPrime():
    n = int(input("Enter a number:"))
    c = 0
    for i in range(2, n):
        if n % i == 0:
            c += 1
    if c == 0:
        return 'Prime'
    else:
        return 'Not Prime'
isPrime()

Enter a number: 23


'Prime'

In [ ]:
# Built-in Function:-

In [51]:
#print
print("Hello World")

Hello World


In [53]:
max(12,34,2345,2343,23,1213435)
#maximum value ko return karta hai

1213435

In [57]:
min(12,4245,6765432,1,0.23)

0.23

In [62]:
sum((2,34,234,42,354,63,5,34345))

35079

In [63]:
#len :- No of elements ko return karta hai
len('Hello')

5

In [64]:
type(2.5)

float

In [65]:
range(1,11)

range(1, 11)

In [67]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# NumPy(Numerical Python):-
<pre>
Numpy is a python library which is use to perform different mathematical operations on arrays.

Array is denoted with '[ ]'.It is ordered(Index posi is fix),nutable(items can be modified) and homogeneous(items of similar datatypes)
collection of items
</pre>

In [79]:
import numpy as np
np.__version__


'2.4.6'

In [82]:
!pip install numpy==1.26.4

ERROR: Could not find a version that satisfies the requirement numpy==1.26.4 (from versions: none)
ERROR: No matching distribution found for numpy==1.26.4


# Creating 1D array:-

In [84]:
#Creating 1D array:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [85]:
type(a)

numpy.ndarray

In [86]:
a = np.array([1,2.4,23,56.7,False])
a

array([ 1. ,  2.4, 23. , 56.7,  0. ])

## if we will try to take heterogeneous elements in a array elements to homogeneous elements based on the priority

In [87]:
a = np.array([1,'cat',3.5,23,True])
a

array(['1', 'cat', '3.5', '23', 'True'], dtype='<U32')

In [89]:
a = np.array(['cat','bat','gum','aeroplane'],dtype='<U2')
a

array(['ca', 'ba', 'gu', 'ae'], dtype='<U2')

# what is dtype(dtype='<U32')??

# 2)Tuple to Array:-

In [91]:
t = np.array((1,12,34,5,6,7))
t

array([ 1, 12, 34,  5,  6,  7])

# 3)Set to Array:-

In [98]:
s = np.array({1,2,3,4,5,6,7,61,3,3,3,2,2})
s
# Set ko hum array mein convert nahi kar skate

array({1, 2, 3, 4, 5, 6, 7, 61}, dtype=object)

# 4)Dictionary to Array

In [100]:
d = np.array({
    'a' : 12,
    'b' : 1,
    'c' : 2
    
})
d

array({'a': 12, 'b': 1, 'c': 2}, dtype=object)

# Creating 2D-Array:-


### 1) List to array:-


In [101]:
a = np.array([[12,3,5],[1223,45,67]])
a

array([[  12,    3,    5],
       [1223,   45,   67]])

## 2)Tuple to array:-

In [102]:
t = np.array([(1,2,3),(4,5,6)])
t

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a = np.array([[12,3,5],(4,5,6)])
a

array([[12,  3,  5],
       [ 4,  5,  6]])

In [105]:
a = np.array([{1,23,3},{1,3,5}])
a

array([{1, 3, 23}, {1, 3, 5}], dtype=object)

# Array Attribute:-
## shape - returns the shape of array

In [108]:
t.shape

(2, 3)

In [110]:
t.size
# size - total number of elements return karta hai

6

In [111]:
t.ndim

2

In [112]:
a = np.array([[[[[1,2,3]]]]])
a.ndim

5

In [122]:

a = np.array([1,2,4], ndmin = 64)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                                                      2,
                                                                      4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [126]:
print(np.maxdims)

AttributeError: module 'numpy' has no attribute 'maxdims'

In [125]:
#arange :- It returns a 1D array 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [140]:
np.zeros((5,5),dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [141]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [143]:
np.ones(6,dtype = "int")

array([1, 1, 1, 1, 1, 1])

In [147]:
np.ones((6,6),dtype = "int")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [148]:
np.full((5,5),8)
# matrix cerate karne ke liye use hota hai aur hum arrray ke andar kuch v add karskte hai...

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [153]:
np.full((5,5),"🥶")

array([['🥶', '🥶', '🥶', '🥶', '🥶'],
       ['🥶', '🥶', '🥶', '🥶', '🥶'],
       ['🥶', '🥶', '🥶', '🥶', '🥶'],
       ['🥶', '🥶', '🥶', '🥶', '🥶'],
       ['🥶', '🥶', '🥶', '🥶', '🥶']], dtype='<U1')

In [154]:
#identity matrix:- diagonal elements non zero and baki sab elements zero
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [155]:
np.eye(5,dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [156]:
#linspace - ye return karta hai equally distributed numbers from a given range
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [160]:
np.linspace(0,100,17)

array([  0.  ,   6.25,  12.5 ,  18.75,  25.  ,  31.25,  37.5 ,  43.75,
        50.  ,  56.25,  62.5 ,  68.75,  75.  ,  81.25,  87.5 ,  93.75,
       100.  ])