# NLP(Natural Language Processing):-
<pre>
    It is basically two types.
        1) NLU(Natural Langugae Understanding)
        2) NLG(NAtural Language Generation)
    NLP can be done in 2 ways. <i>One is By speech or By text.</i>
    e.g.:- Alexa, Siri, Google Keyborad
</pre>
## Basic Terminology used in NLP:-
<pre>
    1) Corpus - Large and Structured set of text used for linguistic research or NLP
    2) Document - A string from corpus stored in a list
    3) Word - A string from document 
    4) Vocabulary - Unique words in the document
    5) Vector - A string which have magnitude and direction(Magnitude means in a string / sentence which word has more focus)
    6) Stopwords - Commonly used words 
    7) Tokens
</pre>
### Steps involved in NLU/text preprocessing:-
<pre>
    1) Tokenization 
    2) Steaming 
    3) Lematization
    4) POS(Parts Of Speech) tags
    5) NER(Named Entity Recognition)
    6) Chunking
</pre>

### 1)Tokenization:-
<pre>breaking the big sentences into smaller units call tokens.
 <i>   It's two types:-
    1)sent_tokenize() - It's for sentence
    2)word_tokenize() - Its for word
     e.g. :- "God is Great" After tokenization It will be ['God','is','Great']
             
 </i>
</pre>

### 2)Steaming:-
<pre>
    It is used to normalize the words into their root / base form by removing suffixes.
    In this process it does not give perfect words thats why we use Lemmatization.
    e.g. :- studied = studi (which is not a proper word)
</pre>

### 3)Lemmatization:-
<pre>
    Converts words into their meaningful dictionary form is known as Lemma.Its is similar to steaming but O/P of lemmatization is a proper word.
    e.g. :- weighted = weight (It is a proper word)
            studied = study 
</pre>

### 4)POS tags:-
<pre>
    It is used to assigns grammatical roles to the words.
    e.g.:- The cat killed the rat.
</pre>

### 5)NER:-
<pre>
    It is a process of detecting important named entities.
    e.g.:- 'Search something on the <b>Google</b>.' - here google refers to a browser.
           'Sundar Pichai is the CEO of <b>Google</b>.' - here google refers to a organization.
    
</pre>

### 6)Chunking:-
<pre>
    Picking individiual piece of information and grouping them into a biggeer piece or phrase is called chunkimg.
    e.g. - The extra dark life of <b>ME</b>
</pre>

### NLP:-

In [1]:
import nltk
nltk.download('words')

[nltk_data] Downloading package words to /Users/nexusop03/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [2]:
txt = "God is Great.I love God"
print(txt)

God is Great.I love God


In [3]:
#Tokenization:-
from nltk import sent_tokenize
sent_tokenize(txt)

['God is Great.I love God']

In [4]:
from nltk import word_tokenize
word_tokenize(txt)

['God', 'is', 'Great.I', 'love', 'God']

In [5]:
# Stemming:- It finds nearest rootword by spelling
from nltk import PorterStemmer
ps = PorterStemmer()

In [6]:
ps.stem('God')

'god'

In [7]:
ps.stem('CARS')

'car'

In [8]:
ps.stem('Studied')

'studi'

In [9]:
ps.stem('learning')

'learn'

In [10]:
ps.stem('went')

'went'

In [11]:
ps.stem('gone')

'gone'

In [12]:
#Lemmatization:-
from nltk import WordNetLemmatizer
lm = WordNetLemmatizer()

In [13]:
lm.lemmatize('went','v')

'go'

In [14]:
lm.lemmatize('eaten','v')

'eat'

In [15]:
lm.lemmatize('studied','v')

'study'

In [16]:
lm.lemmatize('goodness','v')

'goodness'

In [17]:
from nltk.corpus import stopwords
stopwords.words('hinglish')

['a',
 'aadi',
 'aaj',
 'aap',
 'aapne',
 'aata',
 'aati',
 'aaya',
 'aaye',
 'ab',
 'abbe',
 'abbey',
 'abe',
 'abhi',
 'able',
 'about',
 'above',
 'accha',
 'according',
 'accordingly',
 'acha',
 'achcha',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 'agar',
 'ain',
 'aint',
 "ain't",
 'aisa',
 'aise',
 'aisi',
 'alag',
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'andar',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'ap',
 'apan',
 'apart',
 'apna',
 'apnaa',
 'apne',
 'apni',
 'appear',
 'are',
 'aren',
 'arent',
 "aren't",
 'around',
 'arre',
 'as',
 'aside',
 'ask',
 'asking',
 'at',
 'aur',
 'avum',
 'aya',
 'aye',
 'baad',
 'baar',
 'bad',
 'bahut',
 'bana',
 'banae',
 'banai',
 'banao',
 'banaya',
 'banaye',
 'banayi',
 'banda',
 'bande',
 'bandi',
 'bane',
 'bani',
 'bas',
 'bata',
 'bat

In [18]:
print(stopwords.fileids())

['albanian', 'arabic', 'azerbaijani', 'basque', 'belarusian', 'bengali', 'catalan', 'chinese', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'greek', 'hebrew', 'hinglish', 'hungarian', 'indonesian', 'italian', 'kazakh', 'nepali', 'norwegian', 'portuguese', 'romanian', 'russian', 'slovene', 'spanish', 'swedish', 'tajik', 'tamil', 'turkish', 'uzbek']


In [19]:
# POS tags :-
txt = 'Mount Everest is the highest peak in the world'
print(txt)

Mount Everest is the highest peak in the world


In [20]:
txt_token = word_tokenize(txt)
txt_token

['Mount', 'Everest', 'is', 'the', 'highest', 'peak', 'in', 'the', 'world']

In [21]:
txt_tag = nltk.pos_tag(txt_token)
txt_tag

[('Mount', 'NNP'),
 ('Everest', 'NNP'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('highest', 'JJS'),
 ('peak', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('world', 'NN')]

In [22]:
# ne_chunk:-
txt = 'Narendra Modi is the Prime Minister of India'
print(txt)

Narendra Modi is the Prime Minister of India


In [23]:
txt_token = word_tokenize(txt)
txt_token

['Narendra', 'Modi', 'is', 'the', 'Prime', 'Minister', 'of', 'India']

In [24]:
txt_tag = nltk.pos_tag(txt_token)
txt_tag

[('Narendra', 'NNP'),
 ('Modi', 'NNP'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('Prime', 'NNP'),
 ('Minister', 'NNP'),
 ('of', 'IN'),
 ('India', 'NNP')]

In [25]:
from nltk import ne_chunk
txt_chunk = ne_chunk(txt_tag)
print(txt_chunk)

(S
  (PERSON Narendra/NNP)
  (ORGANIZATION Modi/NNP)
  is/VBZ
  the/DT
  Prime/NNP
  Minister/NNP
  of/IN
  (GPE India/NNP))


## Vectorizer:-
<pre>
    This technique used to convert text into numerical vectors so that machine learning algo can process text data.
    It is of 2 types:-
    1) count vectorizer
    2) TFIDF vectorizer
</pre>
### Count Vectorizer:-
<pre>
    It creates a vocabulary of all unique words and count how many time each word appear in a document.
    It converts all the character into lower case.
    It takes the unique words from the sentence and creates a sparse matrix.
    It removes all the stopwords from the sentence
    Arrange alphabatically
    
    Sparse Matrix:- 
</pre>

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
txt = ["I love singing and I love painting."]
x = cv.fit_transform(txt)
x

<1x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [27]:
print(x)

  (0, 1)	2
  (0, 3)	1
  (0, 0)	1
  (0, 2)	1


In [28]:
print(cv.vocabulary_)

{'love': 1, 'singing': 3, 'and': 0, 'painting': 2}


In [29]:
print(x.toarray())

[[1 2 1 1]]


In [30]:
txt = ["I love singing and I love painting.","I love ice ceram"]
txt

['I love singing and I love painting.', 'I love ice ceram']

In [31]:
y = cv.fit_transform(txt)
y

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [32]:
print(y)

  (0, 3)	2
  (0, 5)	1
  (0, 0)	1
  (0, 4)	1
  (1, 3)	1
  (1, 2)	1
  (1, 1)	1


In [33]:
print(cv.vocabulary_)

{'love': 3, 'singing': 5, 'and': 0, 'painting': 4, 'ice': 2, 'ceram': 1}


In [34]:
print(y.toarray())

[[1 0 0 2 1 1]
 [0 1 1 1 0 0]]


## TF-IDF:-(Term Frequency-Inverse Document Frequency)