# Random Numbers 

In [3]:
import numpy as np

In [4]:
# returns a random value between 0 and 1 
np.random.rand()

0.09085605256166118

In [5]:
# returns a 1D array of random numbers between 0 and 1.
np.random.rand(4)

array([0.84814311, 0.63774403, 0.83571329, 0.03039177])

In [8]:
np.random.rand(3,4)

array([[0.11517362, 0.71283362, 0.21831952, 0.81817831],
       [0.02608199, 0.90970232, 0.92395707, 0.22357765],
       [0.47760974, 0.48262835, 0.26676149, 0.81825505]])

In [11]:
np.random.rand(3,4)*100

array([[76.48128705, 11.57896851, 36.78887004, 86.16229486],
       [45.28386664, 77.75820371,  8.98984323, 40.87872452],
       [83.15033644, 12.33611998, 33.1739818 ,  7.95854612]])

In [13]:
np.random.randint(1,20)

16

In [15]:
np.random.randint(1,20,size=8)

array([ 1, 18, 13, 10, 12,  4, 19, 14])

In [17]:
np.random.randint(3,40,(5,6))

array([[26, 25, 22, 35,  7, 26],
       [39, 17, 25, 16, 22,  8],
       [23, 17,  5, 31, 35,  6],
       [16, 23,  6, 26, 19, 27],
       [20, 13, 38, 17,  9, 21]])

# Mathematical Functions 

In [25]:
a= np.array([23,75,57,50,81])
b = np.array([4,5,6,7,3])


In [26]:
a+b

array([27, 80, 63, 57, 84])

In [27]:
# add - Addition
np.add(a,b)

array([27, 80, 63, 57, 84])

In [29]:
np.subtract(a,b)

array([19, 70, 51, 43, 78])

In [30]:
np.multiply(a,b)

array([ 92, 375, 342, 350, 243])

In [31]:
np.divide(a,b)

array([ 5.75      , 15.        ,  9.5       ,  7.14285714, 27.        ])

In [32]:
np.floor_divide(a,b)

array([ 5, 15,  9,  7, 27])

In [34]:
np.mod(a,b)

array([3, 0, 3, 1, 0])

In [35]:
# div_mod - floor_divide and mod 
np.divmod(a,b)

(array([ 5, 15,  9,  7, 27]), array([3, 0, 3, 1, 0]))

In [36]:
# log- by default with base e 
np.log(a)

array([3.13549422, 4.31748811, 4.04305127, 3.91202301, 4.39444915])

In [37]:
np.log10(a)

array([1.36172784, 1.87506126, 1.75587486, 1.69897   , 1.90848502])

In [38]:
# sqrt- Square root
np.sqrt(a)

array([4.79583152, 8.66025404, 7.54983444, 7.07106781, 9.        ])

In [40]:
# cbrt- Cube Root
np.cbrt(a)

array([2.84386698, 4.21716333, 3.84850113, 3.6840315 , 4.32674871])

In [41]:
# Power
np.power(b,2)

array([16, 25, 36, 49,  9], dtype=int32)

In [44]:
#Trigonometry
# sin 
np.sin(a)  # in radian

array([-0.8462204 , -0.38778164,  0.43616476, -0.26237485, -0.62988799])

In [45]:
np.sin(90)

0.8939966636005579

In [46]:
np.sin(90*(np.pi/180))  # in degrees

1.0

In [47]:
# cos
np.cos(a)

array([-0.53283302,  0.92175127,  0.89986683,  0.96496603,  0.77668598])

In [48]:
# tan
np.tan(a)

array([ 1.58815308, -0.42070095,  0.48469923, -0.27190061, -0.81099442])

In [51]:
# cot
1/np.tan(a*(np.pi/180))

array([2.35585237, 0.26794919, 0.64940759, 0.83909963, 0.15838444])

# Statistical Function

In [52]:
a = np.array([45,67,20,58,25])
a

array([45, 67, 20, 58, 25])

In [53]:
np.max(a)

67

In [54]:
np.min(a)

20

In [56]:
# argmax- returns index position of max value 
np.argmax(a)

1

In [57]:
np.argmin(a)

2

In [59]:
# sort(ascending order)
np.sort(a)

array([20, 25, 45, 58, 67])

In [61]:
# returns index position in ascending order
np.argsort(a)

array([2, 4, 0, 3, 1], dtype=int64)

In [62]:
a

array([45, 67, 20, 58, 25])

In [63]:
np.flip(a)

array([25, 58, 20, 67, 45])

In [65]:
np.flip(np.sort(a))    # sorting in descending order 

array([67, 58, 45, 25, 20])

In [66]:
np.mean(a)

43.0

In [67]:
np.median(a)

45.0

In [68]:
# std- Standard Deviation
np.std(a)

18.20988742414406

In [69]:
# var- variance
np.var(a)

331.6

In [70]:
b

array([4, 5, 6, 7, 3])

In [71]:
# cumsum- Cumulative summation
np.cumsum(b)

array([ 4,  9, 15, 22, 25])

In [72]:
# cumprod- Cumulative Product
np.cumprod(b)

array([   4,   20,  120,  840, 2520])

In [73]:
np.cumproduct(b)

array([   4,   20,  120,  840, 2520])

In [74]:
# repeat- repeats each element for given no. of time 
a=np.array([1,2,3,4])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [75]:
# tile - repeats whole sequence for given no. of time 
a= np.array([1,2,3,4])
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [76]:
# where
a=np.array([1,2,4,3,4,5,4,4,6,4])
np.where(a==4)

(array([2, 4, 6, 7, 9], dtype=int64),)

In [85]:
# Round off the numbers
np.round(24.7)

25.0

In [79]:
np.round(24.6)

25.0

In [80]:
np.round(24.5)

24.0

In [82]:
np.ceil(24.1)

25.0

In [84]:
np.trunc(24.9)

24.0

# Vector Maths

In [88]:
a= np.array([[1,3],[2,4]])
b= np.array([[5,7],[6,9]])
print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [6 9]]


In [89]:
# dot
np.dot(a,b)

array([[23, 34],
       [34, 50]])

In [91]:
a@b  # Only possible in arrays

array([[23, 34],
       [34, 50]])

In [92]:
np.cross(a,b)

array([-8, -6])

In [93]:
# transpose
np.transpose(a)

array([[1, 2],
       [3, 4]])

In [94]:
a.T

array([[1, 2],
       [3, 4]])

In [95]:
# Indexing and Slicing in 1D Array
a=np.array([45,78,25,99,66])
a

array([45, 78, 25, 99, 66])

In [96]:
a[2]

25

In [97]:
a[-3]

25

In [98]:
a[::2]

array([45, 25, 66])

In [99]:
# Indexing and slicing in 2D Array
b= np.random.randint(1,20,(5,5))
b

array([[12,  4,  5, 16, 18],
       [ 3,  3,  3, 18,  9],
       [19,  5,  4,  9, 17],
       [15, 14, 13,  1,  8],
       [ 1,  6, 11, 14,  2]])

In [100]:
b[2,3]

9

In [102]:
b[3]         #  By default row

array([15, 14, 13,  1,  8])

In [104]:
np.where(b==3)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

In [105]:
# Slicing- var[row_slicing, col_slicing ]
b[1:4:1, 1:4:1]

array([[ 3,  3, 18],
       [ 5,  4,  9],
       [14, 13,  1]])

In [106]:
# Concatenation
a = np.random.randint(1,20,(2,2))
a

array([[13, 17],
       [15, 12]])

In [107]:
b = np.random.randint(1,20,(2,4))
b

array([[ 6, 12, 11, 17],
       [16, 14, 11, 11]])

In [108]:
c = np.random.randint(1,20,(4,4))
c

array([[ 5, 17,  8,  8],
       [16, 11, 16,  3],
       [ 7, 17, 19, 17],
       [16, 19, 13, 11]])

In [110]:
np.concatenate((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [111]:
np.concatenate((a,b),axis=1)

array([[13, 17,  6, 12, 11, 17],
       [15, 12, 16, 14, 11, 11]])

In [112]:
# axis=0 (row wise) (by default)
np.concatenate((b,c))

array([[ 6, 12, 11, 17],
       [16, 14, 11, 11],
       [ 5, 17,  8,  8],
       [16, 11, 16,  3],
       [ 7, 17, 19, 17],
       [16, 19, 13, 11]])

In [ ]:
# Stack:-
# Horizontal Stacking (axis=1) -> Row Equal
# Vertical Stacking   (axis=0) -> Column Equal
# Depth Stacking               -> Both must be equal

In [114]:
np.hstack((a,b))

array([[13, 17,  6, 12, 11, 17],
       [15, 12, 16, 14, 11, 11]])

In [115]:
np.vstack((b,c))

array([[ 6, 12, 11, 17],
       [16, 14, 11, 11],
       [ 5, 17,  8,  8],
       [16, 11, 16,  3],
       [ 7, 17, 19, 17],
       [16, 19, 13, 11]])